version: "1"
services:
  db:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    depends_on:
      - db
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm start"
volumes:
  mysql-data:
